### ISSUE TITLE
as-table does not recognize ansicolors when calculating column width

### ISSUE THREAD

**Issue by kroitor** [xpl/as-table#1]
<img width="1249" alt="screen shot 2017-07-20 at 19 16 49" src="https://user-images.githubusercontent.com/1294454/28427882-3291da08-6d80-11e7-8c53-7494bb6d843d.png">

**Comment by xpl** [comment]
Fixed, now fully supports colors (in cells, in headers, in delimiter). You can now also customize the header separator symbol and title rendering style):

<img width="179" alt="screen shot 2017-07-21 at 23 46 14" src="https://user-images.githubusercontent.com/1707/28481945-dcb0f8d6-6e6e-11e7-896e-dfad40662daf.png">
